server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/boot
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml,classpath:mapping/ext/*.xml
  type-aliases-package: com.jxm.model
logging:
  level:
    com.jxm: debug
  pattern:
    console: "%date{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  path: /var/logs          # 在/var/logs目录下生成spring.log文件
  file: /var/logs/boot.log # 在/var/logs目录下生成boot.log文件
#pagehelper分页插件
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql